# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FireBoard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FireBoard

pod 'Firebase/Analytics'
pod 'FirebaseUI/Auth'
pod 'FirebaseUI/Email'

end
